### ISSUE TITLE
Entity has no state

### ISSUE THREAD

**Issue by marcovolt** [klausj1/homeassistant-statistics#8] opened 2024-02-21 09:49 UTC
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 87

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018 at 01:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
instance_id | 837ab25cbf944202946611186c9b3f4e
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 916.2 GB
disk_used | 350.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.0), File editor (5.8.0), Advanced SSH & Web Terminal (17.1.0), Log Viewer (0.17.0), InfluxDB (5.0.0), Home Assistant Google Drive Backup (0.103.1), Studio Code Server (5.15.0), Grafana (9.1.3), Mosquitto broker (6.4.0), Glances (0.21.0), RPC Shutdown (2.4), Syncthing (1.18.2), WireGuard (0.10.2), Samba Backup (5.2.0), rsync (1.7.0), ESPHome (2024.2.0), RTSPtoWeb - WebRTC (1.4.0), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.8.0), A9 Camera fake server (2.4), AdGuard Home (5.0.3), Node-RED (17.0.7), Zigbee2MQTT (1.35.3-1), LibreTiny ESPHome (2023.9.0-dev)

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 61
views | 85
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 30, 2023 at 15:23
-- | --
current_recorder_run | February 21, 2024 at 02:37
estimated_db_size | 17789.49 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 3.3.6 (6a494ae)
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.15
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 22

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/klausj1/homeassistant-statistics/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, thanks for your work on this import service.
I imported the file and I have the green check at the end, here below a string of my test file (616 lines, tab separated):
statistic_id	unit	start	min	max	mean
sensor.import_test	EUR	28.02.2023 14:00	19647	19647	19647
The problem is that when I check the entity in developer tool/statistic it shows me "there is no state available for this entity." and the only option from fix button is to delete the entity.
Furthermore the entity is not listed in developer tools/states so is not possible to update the current state.
I see no info about the service in the debug log viewer.

### Reproduction steps

1. import the file from the service
2. check statistic
3. create state - entity not in the list

### Debug logs

```text
---
```

**Comment by klausj1** [comment] 2024-02-21 14:18
The problem is that you can only add statistics for already existing entities. For not existing entities, the :-syntax should be used (like sensor:sensorName instead of sensor.sensorName), but this is not yet working with the integration. I will have a look.

**Comment by klausj1** [comment] 2024-03-17 17:25
Fixed with version 1.0.0. You can now import e.g. sensor:sensorName as well.

**Closed by klausj1** 2024-03-17 17:25 UTC
